---
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Ensure snmpd in installed (Debian)
  ansible.builtin.apt:
    name: snmpd
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure snmpd in installed (RedHat)
  ansible.builtin.package:
    name:
      - net-snmp
      - net-snmp-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy snmpd template
  ansible.builtin.template:
    src: templates/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart snmpd

- name: Download librenms snmpd script
  ansible.builtin.get_url:
    url: >
      https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro
    mode: '0755'
  notify: Restart snmpd
